#!/usr/bin/env bash
# configures any Ubuntu server
# 8.8.8.8 resolves to facebook.com
# 127.0.0.2 resolves to localhost
cp /etc/hosts ~/hosts.new
echo "127.0.0.2         localhost" > ~/hosts.new
echo "8.8.8.8           facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
